name: Publish library

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'assets/**'

env:
  LIBRARY_VERSION: 0.1.${{ github.run_number }}

jobs:
  publish-library:
    if: "!contains(github.event.head_commit.author.email, 'taiui@gmail.com')"
    name: Publish icon libraries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Bump version patch
      run: |
        grep -E "[0-9]+\.[0-9]+\.[0-9]+" ios/FluentIcons.podspec | python3 -c """
        import sys
        import os
        current_version = sys.stdin.read().strip().split(\"'\")[1]
        major, minor, patch = current_version.split('.')
        os.system(f'echo \"NEW_VERSION={major}.{minor}.{int(patch) + 1}\" >> \$GITHUB_ENV') 
        """

    - name: Use Node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11.x

    - run: npm install
      working-directory: importer

    ## Publish
    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version numbers in README.md
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/$NEW_VERSION/g" README.md
        rm README.md.bk

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version number in Podspec
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/$NEW_VERSION/g" ios/FluentIcons.podspec
        rm ios/FluentIcons.podspec.bk

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version number in svg-icons/package.json
      run: |
        sed -i.bk -r "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$NEW_VERSION\"/g" packages/svg-icons/package.json
        rm packages/svg-icons/package.json.bk

    - name: Build SVG library
      run: |
        npm install
        npm run build
      working-directory: packages/svg-icons

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: packages/svg-icons/package.json

    - name: Update icon sheet
      run: python3 generate_icons_md.py
    
    - name: Config git credentials
      run: git config user.email "taiui@gmail.comm" && git config user.name "Build System"

    - name: Commit version number change
      run: |
        git add -A
        git commit -m "Release $NEW_VERSION"
        
    - name: Tag release
      run: git tag "$NEW_VERSION"

    - name: Push release
      run: |
        REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push $REMOTE_REPO HEAD:main --follow-tags --tags